version: "3.8"
services:
  backend:
    build: ./back-end
    image: krelli-backend-image
    container_name: krelli-backend-container
    ports:
      - "3001:3001"
    restart: always
    env_file:
      - back-end/.env
  frontend:
    build: ./front-end
    image: krelli-frontend-image
    container_name: krelli-frontend-container
    ports:
      - "5001:5001"
    restart: always
    env_file:
      - front-end/.env